name: volt_sentinel_lakehouse
version: 1.0.0
config-version: 2
profile: volt_sentinel_lakehouse

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
macro-paths: ["macros"]

models:
  volt_sentinel_lakehouse:
    bronze:
      +materialized: view
    silver:
      +materialized: incremental
    gold:
      +materialized: incremental
